name: Continuous Deployment

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app
        uses: actions/checkout@v2
      - name: Deploy to Netlify
        run: npx netlifyctl deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
          