name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - run: npm install
      - run: npm run migrate up
      - uses: netlify/actions/deploy@v1
        with:
          token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
