name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install IBM Cloud CLI
        uses: IBM/actions-ibmcloud-cli@0.0.8
        with:
          APIKEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          CLOUD_REGION: us-south
          script: |
            cd ~/forumapi
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forumapi
