name: Continuous Deployment

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app
        uses: actions/checkout@v2
      - name: Deploy to Netlify
        uses: netlify/actions/cli@v1
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          